services:
  web:
    build:
      context: .
      target: builder
    container_name: herenciapp_prod
    # restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy # Wait for the database to be healthy before starting the web service
  db:
    image: postgres:15-alpine # Alpine is small version, saving disk space
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${MOCK_DB_USER}
      - POSTGRES_PASSWORD=${MOCK_DB_PASSWORD}
      - POSTGRES_DB=${MOCK_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      # Production-grade health check: makes sure the DB is listening and accepting passwords
      test: ["CMD-SHELL", "pg_isready -U ${MOCK_DB_USER} -d ${MOCK_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: