services:
  web:
    build:
      context: .
      target: builder
    container_name: herenciapp_prod
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
  db:
    image: postgres:15-alpine # Alpine is small version, saving disk space
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${MOCK_DB_USER}
      - POSTGRES_PASSWORD=${MOCK_DB_PASSWORD}
      - POSTGRES_DB=${MOCK_DB_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres_data: