"""add supplier column to expenses table

Revision ID: 4fa3bcc9d3b8
Revises: c2ce435f98ef
Create Date: 2026-09-22 04:56:48.799342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fa3bcc9d3b8'
down_revision: Union[str, Sequence[str], None] = 'c2ce435f98ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('supplier', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'supplier')
    # ### end Alembic commands ###
