"""add role column to users table

Revision ID: 9f292299a76f
Revises: f2dfddf99bcb
Create Date: 2026-06-07 15:45:01.982685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f292299a76f'
down_revision: Union[str, Sequence[str], None] = 'f2dfddf99bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # first: accept null values
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # remove NULL values in existent fields
    op.execute("UPDATE \"user\" SET role = 'guest' WHERE role IS NULL")
    # upgrade null_False
    op.alter_column('user', 'role', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
