"""create_restaurant_and_orders_tables

Revision ID: af2b5810e086
Revises: 8b08a95f01b9
Create Date: 2026-05-26 07:20:30.924221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af2b5810e086'
down_revision: Union[str, Sequence[str], None] = '8b08a95f01b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_dish', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_main_dish'), 'products', ['main_dish'], unique=False)
    op.create_table('flavor_catalogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flavor_catalogue_product_id'), 'flavor_catalogue', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.SmallInteger(), nullable=False),
    sa.Column('number_of_persons', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('sended', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('discount_motive', sa.Text(), nullable=True),
    sa.Column('tip', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pay_method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'CRYPTO', name='paymethod'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_closed'), 'orders', ['closed'], unique=False)
    op.create_index(op.f('ix_orders_closed_at'), 'orders', ['closed_at'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_delivered_at'), 'orders', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_orders_sended'), 'orders', ['sended'], unique=False)
    op.create_index(op.f('ix_orders_table_no'), 'orders', ['table_no'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('person_number', sa.SmallInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('flavor_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prep_status', sa.Enum('QUEUED', 'COOKING', 'READY', 'PARTIAL_DELIVERED', 'DELIVERED', name='itemprepstatus'), nullable=False),
    sa.Column('extra_charge', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['flavor_id'], ['flavor_catalogue.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_detail_order_id'), 'order_detail', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_detail_person_number'), 'order_detail', ['person_number'], unique=False)
    op.create_index(op.f('ix_order_detail_prep_status'), 'order_detail', ['prep_status'], unique=False)
    op.alter_column('verificationtoken', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verificationtoken', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_detail_prep_status'), table_name='order_detail')
    op.drop_index(op.f('ix_order_detail_person_number'), table_name='order_detail')
    op.drop_index(op.f('ix_order_detail_order_id'), table_name='order_detail')
    op.drop_table('order_detail')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_table_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_sended'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivered_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_closed_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_closed'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_flavor_catalogue_product_id'), table_name='flavor_catalogue')
    op.drop_table('flavor_catalogue')
    op.drop_index(op.f('ix_products_main_dish'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
