"""added selection str field to OrderDetail

Revision ID: cce1eeede1a3
Revises: 9f292299a76f
Create Date: 2026-06-07 17:01:07.293491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cce1eeede1a3'
down_revision: Union[str, Sequence[str], None] = '9f292299a76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('selection', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_detail', 'selection')
    # ### end Alembic commands ###
