"""create_expenses_table

Revision ID: d4f1a2b3c4e5
Revises: 9f292299a76f
Create Date: 2026-08-18 12:53:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4f1a2b3c4e5'
down_revision: Union[str, Sequence[str], None] = '9f292299a76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('expense', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('category', sa.Enum('food', 'beverages', 'desserts', 'operation', name='expensecategory'), nullable=True),
        sa.Column('quantity', sa.Float(), nullable=True),
        sa.Column('total', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
