"""add unique constraint to flavor catalogue

Revision ID: f2dfddf99bcb
Revises: 99939d7d6a20
Create Date: 2026-06-01 07:57:12.654927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2dfddf99bcb'
down_revision: Union[str, Sequence[str], None] = '99939d7d6a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # adding a try/except block to avoid pipeline breaks
    try:
        op.create_unique_constraint('uq_product_flavor_description', 'flavor_catalogue', ['product_id', 'description'])
    except Exception as e:
        print(f"Error occurred while creating unique constraint: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_flavor_description', 'flavor_catalogue', type_='unique')
    # ### end Alembic commands ###
