"""main dish unique

Revision ID: fb4c4d042aa5
Revises: af2b5810e086
Create Date: 2026-05-31 08:46:29.203793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb4c4d042aa5'
down_revision: Union[str, Sequence[str], None] = 'af2b5810e086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_main_dish'), table_name='products')
    op.create_index(op.f('ix_products_main_dish'), 'products', ['main_dish'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_main_dish'), table_name='products')
    op.create_index(op.f('ix_products_main_dish'), 'products', ['main_dish'], unique=False)
    # ### end Alembic commands ###
